# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:
 global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C ./ci/with-compiler.cmd"
  matrix:
    - PYTHON: "C:\\Python27-conda32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-conda64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      DISTUTILS_USE_SDK: "1"

    - PYTHON: "C:\\Python36-conda64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\share\\mingwpy\\lib;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "conda update --yes --quiet conda"
  - "conda -V"
  - "conda create --yes -n condaenv python=%PYTHON_VERSION%"
  - "activate condaenv"
  # workaround for conda-forge/hdf5-feedstock#41
  - "conda install --yes -n condaenv hdf5"
  - "conda config --add channels conda-forge"
  # install pycalphad and dependencies
  - "conda install --yes -n condaenv --quiet pip setuptools nose numpy pandas scipy sympy pyparsing matplotlib xarray dask dill"
  - "conda install --yes -n condaenv --quiet tinydb cython"
  - "%WITH_COMPILER% python -m pip install -e ."

build: false

test_script:
  - "%WITH_COMPILER% python -c \"import nose ; nose.main()\" -s -v pycalphad"
