# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:
  matrix:
    - PYTHON: "C:\\Python27-conda32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-conda64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-conda64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\share\\mingwpy\\lib;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "conda install --yes --quiet conda=4.3.31"
  - "conda config --system --add pinned_packages defaults::conda"
  - "conda -V"
  - "conda create --yes -n condaenv python=%PYTHON_VERSION%"
  - "activate condaenv"
  # workaround for conda-forge/hdf5-feedstock#41
  - "conda install --yes -n condaenv hdf5"
  - "conda config --add channels conda-forge"
  - "conda config --add channels msys2"
  - "conda config --add channels pycalphad"
  # install pycalphad and dependencies
  - "conda install --yes -n condaenv --quiet pip setuptools nose numpy pandas scipy sympy pyparsing matplotlib xarray dask dill 'tinydb>=3.8' cython cyipopt m2w64-toolchain libpython symengine python-symengine"
  - "pip install -e ."

build: false

test_script:
  - "python -c \"import nose ; nose.main()\" -s -v pycalphad"
