# Environment that installs all pycalphad dependencies and test suite dependencies
name: test
channels:
  - conda-forge
  - pycalphad
dependencies:
  # NOTE: please try to keep any depedencies in alphabetic order so they may
  # be easily compared with other dependency lists
  # NOTE: these dependencies may differ in name from the conda-forge and
  # pycalphad Anaconda channels  from those on PyPI (i.e. those found in
  # `setup.py`). For example, conda-forge/symengine gives the C++ SymEngine
  # library, while conda-forge/python-symengine provides the Python package
  # called `symengine`.
  - cyipopt
  - cython>=0.24
  - ipopt=3.12.13
  - matplotlib
  - numpy>=1.13
  - pyparsing
  - python>=3.6
  - python-symengine=0.6.1
  - scipy
  # We don't import the C++ symengine library directly in pycalphad, but
  # phase_rec.FastFunction class implementation is coupled to SymEngine's
  # function pointer API, so we pin the version here.
  - symengine=0.6.0
  - sympy=1.5.1
  - tinydb>=3.8
  - xarray>=0.11.2
  # Dependences for tests only below
  - coveralls
  - pytest
  - pytest-cov
  # Documentation dependences
  - ipython  # for pygments syntax highlighting
  - sphinx
  - sphinx_rtd_theme
